language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - pip install pytest-cov
  - cd python

before_script:
  - pip install docker-compose

script:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"
  - docker-compose run --rm app sh -c "py.test -v --cov=maths"