language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - pip install docker-compose
  - docker-compose up -d


script:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"